=== OferSpivak/BattleShipGame/src/resources/BattleShipGame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BattleShipGame">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GameType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Basic"/>
                            <xs:enumeration value="Advance"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="boardSize" type="xs:int"/>
                <xs:element name="shipTypes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="shipType" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Regular"/>
                                                    <xs:enumeration value="Complex"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:int"/>
                                        <xs:choice>
                                            <xs:element name="length" type="xs:int"/>
                                            <xs:element name="path">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="firstAxisLength" type="xs:int"/>
                                                        <xs:element name="secondAxisLength" type="xs:int"/>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="boards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="board" minOccurs="2" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ship" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string"/>
                                                    <xs:element name="position">
                                                        <xs:complexType>
                                                            <xs:attribute name="x" type="xs:int"/>
                                                            <xs:attribute name="y" type="xs:int"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="direction">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Row"/>
                                                                <xs:enumeration value="Column"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="score" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OferSpivak/BattleShipGame/BaseGame/src/resources/baseInput.xml
<?xml version="1.0"?>
<BattleShipGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BattleShipGame.xsd">
    <GameType>BASIC</GameType>
    <boardSize>12</boardSize>
    <shipTypes>
        <shipType id="A">
            <category>REGULAR</category>
            <amount>1</amount>
            <length>4</length>
            <score>1</score>
        </shipType>
        <shipType id="B">
            <category>REGULAR</category>
            <amount>2</amount>
            <length>3</length>
            <score>1</score>
        </shipType>
        <shipType id="C">
            <category>REGULAR</category>
            <amount>3</amount>
            <length>2</length>
            <score>1</score>
        </shipType>
        <shipType id="D">
            <category>REGULAR</category>
            <amount>4</amount>
            <length>1</length>
            <score>1</score>
        </shipType>
        <!--<shipType id="E">
            <category>Complex</category>
            <amount>4</amount>
            <path>
                <firstAxisLength>2</firstAxisLength>
                <secondAxisLength>3</secondAxisLength>
            </path>
        </shipType>-->
    </shipTypes>
    <boards>
        <board>
            <ship>
                <shipTypeId>A</shipTypeId>
                <position x="1" y="1" />
                <direction>ROW</direction>
            </ship>
            <ship>
                <shipTypeId>B</shipTypeId>
                <position x="2" y="2" />
                <direction>COLUMN</direction>
            </ship>
        </board>
        <board>
            <ship>
                <shipTypeId>A</shipTypeId>
                <position x="1" y="1" />
                <direction>COLUMN</direction>
            </ship>
            <ship>
                <shipTypeId>B</shipTypeId>
                <position x="2" y="2" />
                <direction>ROW</direction>
            </ship>
        </board>
    </boards>
</BattleShipGame>

=== OferSpivak/BattleShipGame/src/resources/baseInput.xml
<?xml version="1.0"?>
<BattleShipGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BattleShipGame.xsd">
    <type>Basic</type>
    <shipTypes>
        <shipType name="A">
            <type>Regular</type>
            <length>4</length>
            <amount>1</amount>
        </shipType>
        <shipType name="B">
            <type>Regular</type>
            <length>3</length>
            <amount>2</amount>
        </shipType>
        <shipType name="C">
            <type>Regular</type>
            <length>2</length>
            <amount>3</amount>
        </shipType>
        <shipType name="D">
            <type>Regular</type>
            <length>1</length>
            <amount>4</amount>
        </shipType>
    </shipTypes>
    <boards>
        <board>
            <ship>
                <type>A</type>
                <position x="1" y="1" />
                <direction>Row</direction>
                <score>1</score>
            </ship>
            <ship>
                <type>B</type>
                <position x="2" y="2" />
                <direction>Column</direction>
                <score>1</score>
            </ship>
        </board>
        <board>
            <ship>
                <type>A</type>
                <position x="1" y="1" />
                <direction>Column</direction>
                <score>1</score>
            </ship>
            <ship>
                <type>B</type>
                <position x="2" y="2" />
                <direction>Row</direction>
                <score>1</score>
            </ship>
        </board>
    </boards>
</BattleShipGame>

=== OferSpivak/BattleShipGame/BaseGame/src/resources/baseInput5.xml
<?xml version="1.0"?>
<BattleShipGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BattleShipGame.xsd">
    <GameType>Basic</GameType>
    <boardSize>5</boardSize>
    <shipTypes>
        <shipType name="A">
            <type>Regular</type>
            <amount>1</amount>
            <length>4</length>
            <score>1</score>
        </shipType>
        <shipType name="B">
            <type>Regular</type>
            <amount>2</amount>
            <length>3</length>
            <score>1</score>
        </shipType>
    </shipTypes>
    <boards>
        <board>
            <ship>
                <type>A</type>
                <position x="1" y="1" />
                <direction>ROW</direction>
            </ship>
            <ship>
                <type>B</type>
                <position x="3" y="1" />
                <direction>COLUMN</direction>
            </ship>
            <ship>
                <type>B</type>
                <position x="5" y="3" />
                <direction>ROW</direction>
            </ship>
        </board>
        <board>
            <ship>
                <type>A</type>
                <position x="1" y="1" />
                <direction>ROW</direction>
            </ship>
            <ship>
                <type>B</type>
                <position x="3" y="1" />
                <direction>COLUMN</direction>
            </ship>
            <ship>
                <type>B</type>
                <position x="5" y="3" />
                <direction>ROW</direction>
            </ship>
        </board>
    </boards>
</BattleShipGame>
